### ISSUE TITLE
docker/kill-conn-grep durable-consumer

### ISSUE THREAD

**Issue by wlund-pivotal** [rabbitmq/workloads#22]
This script does not seem to be working correctly and it's hard to understand the expected result.  I believe its supposed to be only the durable-consumer that gets killed but when I run the script I get the following output:

` docker/list-conn

172.18.0.1:52962 -> 172.18.0.3:5672	durable-consumer#9	durable-consumer	rabbit@rmq0
172.18.0.1:52966 -> 172.18.0.3:5672	fire-and-forget#7.publisher	fire-and-forget-producer	rabbit@rmq0
172.18.0.1:52970 -> 172.18.0.3:5672	fire-and-forget#8	fire-and-forget-producer	rabbit@rmq0`

and when it runs you see all connections are deleted:
![Screen Shot 2020-10-12 at 10 41 24 AM](https://user-images.githubusercontent.com/5314240/95775648-a8f1ea00-0c77-11eb-8af1-a946ab6d519c.png)

You'll notice that all instance_ids are incremented, not just durable-consumer:
`172.18.0.1:53142 -> 172.18.0.3:5672	durable-consumer#12	durable-consumer	rabbit@rmq0
172.18.0.1:53146 -> 172.18.0.3:5672	fire-and-forget#13.publisher	fire-and-forget-producer	rabbit@rmq0
172.18.0.1:53150 -> 172.18.0.3:5672	fire-and-forget#14	fire-and-forget-producer	rabbit@rmq0`
(this was after a couple of runs).

**Comment by wlund-pivotal** [comment]
I think I've located the problem to the function rawurlencode().  It does not exist on OSX and I'm having problems finding out how to download the function for OSX.  Can we get this added to the prerequisites section?

**Comment by wlund-pivotal** [comment]
I'm not a strong bash developer by any means but based on what I read there should have been a rawurlencode script in the docker directory that isn't there. Should that have been checked in and wasn't?

**Comment by MarcialRosales** [comment]
The script exists (https://github.com/rabbitmq/workloads/blob/master/resiliency/resilient-spring-cloud-stream/docker/rawurlencode) . And `kill-conn-grep` invokes it here (https://github.com/rabbitmq/workloads/blob/master/resiliency/resilient-spring-cloud-stream/docker/kill-conn-grep#L7) . It could be that the script does not have execution permission ? 

I have set the permission in git so that when you check it out, it is already executable.

**Comment by wlund-pivotal** [comment]
I should have updated you.  I was doing a grep for rawurlencode function and didn't realize it was named urlencode in the rawurlencode script.  However, it was already marked executable and I'm not getting correct results.
@gregoryan and I paired last Thursday and we found that there seemed to be a required argument missing in the script because all connections were killed.  I'll update the issue accordingly. Could we pair tomorrow morning?  I'll send out an invite and see if it works for you.

When the last line  `kill_connections $1` was added to the script it worked:

First:
```
docker/list-conn
172.18.0.1:45994 -> 172.18.0.3:5672	fire-and-forget#23.publisher	fire-and-forget-producer	rabbit@rmq0
172.18.0.1:45998 -> 172.18.0.3:5672	fire-and-forget#24	fire-and-forget-producer	rabbit@rmq0
172.18.0.1:51290 -> 172.18.0.3:5672	durable-consumer#25	durable-consumer	rabbit@rmq0
```
We try the durable-consumer with:

`docker/kill-conn-grep "172.18.0.1:51290 -> 172.18.0.3:5672"`

and get:

```
docker/kill-conn-grep "172.18.0.1:36142 -> 172.18.0.3:5672"
(entry)Killing connections for 172.18.0.1:36142 -> 172.18.0.3:5672
There are 0 messages in the trades.trade-logger queue
(func)Killing connections for 172.18.0.1:36142
/Users/wlund/Dropbox/git-workspace/wxlund/workloads/resiliency/resilient-spring-cloud-stream/docker
Killing connection 172.18.0.1%3A36142%20-%3E%20172.18.0.3%3A5672
```

 You can see that there was a bug but it looks like it was fixed at some point because it's what I'm seeing in the repo now. Now it works whether I pass the name or the user.  It looks like the parameter fixed went in 15 hrs ago so we're good.

**Comment by wlund-pivotal** [comment]
This issue is resolved per adding the parameter and chmod +x on the rawurlencode.
