### ISSUE TITLE
Need JQ added to pre-req

### ISSUE THREAD

**Issue by agregory999** [rabbitmq/workloads#23]
From a fresh Ubuntu VM I needed to install JQ as it wasn't there by default.

**Comment by michaelklishin** [comment]
@agregory999 what is being requested here? If it's a doc update you are welcome to submit a PR.

**Comment by MarcialRosales** [comment]
@agregory999 are you referring to the work done under resiliency/resilient-spring-cloud-stream? If so, this commit solves it. Please check it out:
https://github.com/rabbitmq/workloads/commit/b89f449fc183d33835d7ece57c6c8e763d1e79a5

It states it in the Readme and also the scripts that uses curl and/or jq checks that both commands are installed.
