### ISSUE TITLE
Resiliency - Move resiliency folder to its own repository under rabbitmq org

### ISSUE THREAD

**Issue by MarcialRosales** [rabbitmq/workloads#29]

**Comment by lukebakken** [comment]
https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by MarcialRosales** [comment]
Nice one ! Thanks @lukebakken

**Comment by lukebakken** [comment]
I don't have permissions in the RabbitMQ org to create a new repository.

@michaelklishin ? Would you mind creating `rabbitmq/resiliency-workloads` ?

**Comment by michaelklishin** [comment]
Done https://github.com/rabbitmq/resiliency-workloads.

**Comment by lukebakken** [comment]
@michaelklishin unfortunately I get a `404` when I visit that link.

**Comment by michaelklishin** [comment]
@lukebakken oops, no teams had the access to the repo. Try again?

**Comment by lukebakken** [comment]
All good! Thanks @michaelklishin

**Comment by lukebakken** [comment]
Done - https://github.com/rabbitmq/resiliency-workloads

**Comment by lukebakken** [comment]
@michaelklishin one more small thing... would you mind making https://github.com/rabbitmq/resiliency-workloads public?

**Comment by lukebakken** [comment]
Thanks again @michaelklishin
